# backend/app/models/location_model.py

from pydantic import BaseModel, Field
from typing import Optional

class Location(BaseModel):
    id: str = Field(..., description="Unique identifier for the location (e.g., generated by the Overpass API)")
    name: str = Field(..., description="Name of the location (e.g., cafe or museum name)")
    city: str = Field(..., description="City where the location is situated")
    amenity: str = Field(..., description="Type of amenity (e.g., cafe, museum, park)")
    lat: float = Field(..., description="Latitude coordinate of the location")
    lon: float = Field(..., description="Longitude coordinate of the location")
    description: Optional[str] = Field(None, description="Optional description or additional details about the location")

    class Config:
        json_schema_extra = {
            "example": {
                "id": "123abc",
                "name": "Central Park Cafe",
                "city": "New York",
                "amenity": "cafe",
                "lat": 40.785091,
                "lon": -73.968285,
                "description": "A popular cafe located within Central Park."
            }
        }
