import createClient from 'openapi-fetch';
import type { paths } from './api'; // Generated by openapi-typescript

const URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000';

export const client = createClient<paths>({ baseUrl: URL });
